### ISSUE TITLE
Can I use this crate in an MIT licensed project?

### ISSUE THREAD

**Issue by little-dude** [aweinstock314/rust-clipboard#33]
Hi,

GPL implies I have to distribute the sources of the whole project. But I can I still use an MIT license in my project if I use this crate? I've found this [stackexchange question](http://programmers.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application), and the accepted answers suggests that I have to use GPL:

```
> Because GeSHi is GPL, does my framework have to be GPL?

ANSWER: If you distribute your framework, then YES.
```

That seems a little bit weird to me though.

**Comment by aweinstock314** [comment]
I believe Apache2 is MIT-compatible, and this crate is dual-licensed under Apache2/GPL. The reason I had it initially GPL-licensed is because I translated the x11 clipboard code from xclip's C implementation, which is GPL. 

I plan on eventually rewriting that section to be based on xterm's implementation (MIT-licensed) and the ICCCM documentation, and relicensing this to pure Apache2. I haven't yet had time to do this due to other obligations.
